# -*- coding: utf-8 -*-
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog, QApplication, QTableWidgetItem, QComboBox


class UiMedian(QDialog):

    def __init__(self):
        super().__init__()
        self.setObjectName("Dialog")
        self.resize(1120, 730)
        self.setMinimumSize(QtCore.QSize(1120, 730))
        self.setMaximumSize(QtCore.QSize(1120, 730))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.setFont(font)
        self.title = QtWidgets.QLabel(self)
        self.title.setGeometry(QtCore.QRect(100, 30, 400, 60))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setObjectName("title")
        #多界面框
        self.tabWidget = QtWidgets.QTabWidget(self)
        self.tabWidget.setGeometry(QtCore.QRect(70, 100, 470, 540))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.LMP_tab = QtWidgets.QWidget()
        self.LMP_tab.setObjectName("LMP_tab")
        self.BPD_tab = QtWidgets.QWidget()
        self.BPD_tab.setObjectName("BPD_tab")
        self.CRL_tab = QtWidgets.QWidget()
        self.CRL_tab.setObjectName("CRL_tab")
        self.IVF_tab = QtWidgets.QWidget()
        self.IVF_tab.setObjectName("IVF_tab")
        self.BC_tab = QtWidgets.QWidget()
        self.BC_tab.setObjectName("B超_tab")
        self.tabWidget.addTab(self.LMP_tab, "")
        self.tabWidget.addTab(self.BPD_tab, "")
        self.tabWidget.addTab(self.CRL_tab, "")
        self.tabWidget.addTab(self.IVF_tab, "")
        self.tabWidget.addTab(self.BC_tab, "")

        #设置为第一个界面
        self.tabWidget.setCurrentIndex(0)
        self.median_table_title()

        self.table_view_setting()
        # self.check_button_setting()
        self.test_item_LMP_setting()
        self.test_item_BPD_setting()
        self.test_item_CRL_setting()
        self.test_item_IVF_setting()
        self.test_item_BC_setting()
        self.retranslateUi()

        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        self.translate = QtCore.QCoreApplication.translate
        self.setWindowTitle("中位数版本设置")
        self.title.setText("中位数版本设置")

        # 表格内容设置
        self.table_title.setText("当前列表： 版本号： ")
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText("孕周/长度")
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText("中位数值")
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText("单位")

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.LMP_tab), "LMP")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.BPD_tab), "BPD")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.CRL_tab), "CRL")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.IVF_tab), "IVF")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.BC_tab), "B超")

        # self.check_butten.setText()"确认"))
        #LMP孕周类型标记物设置
        self.mark_LMP_1.setText("APF_M")
        self.mark_LMP_2.setText("tbhCG_M")
        self.mark_LMP_3.setText("fbhCG_M")
        self.mark_LMP_4.setText("uE3_M")
        self.mark_LMP_5.setText("InhA_M")
        self.mark_LMP_6.setText("PAPPA_M")
        self.mark_LMP_7.setText("NT_E")
        self.mark_LMP_8.setText("AFP_E")
        self.mark_LMP_9.setText("tbhCG_E")
        self.mark_LMP_10.setText("fbhCG_E")
        self.mark_LMP_11.setText("uE3_E")
        self.mark_LMP_12.setText("InhA_E")
        self.mark_LMP_13.setText("PAPPA_E")

        #BPD孕周类型标记物设置
        self.mark_BPD_1.setText("APF_M")
        self.mark_BPD_2.setText("tbhCG_M")
        self.mark_BPD_3.setText("fbhCG_M")
        self.mark_BPD_4.setText("uE3_M")
        self.mark_BPD_5.setText("InhA_M")
        self.mark_BPD_6.setText("PAPPA_M")
        self.mark_BPD_7.setText("NT_E")
        self.mark_BPD_8.setText("AFP_E")
        self.mark_BPD_9.setText("tbhCG_E")
        self.mark_BPD_10.setText("fbhCG_E")
        self.mark_BPD_11.setText("uE3_E")
        self.mark_BPD_12.setText("InhA_E")
        self.mark_BPD_13.setText("PAPPA_E")

        # CRL孕周类型标记物设置
        self.mark_CRL_1.setText("APF_M")
        self.mark_CRL_2.setText("tbhCG_M")
        self.mark_CRL_3.setText("fbhCG_M")
        self.mark_CRL_4.setText("uE3_M")
        self.mark_CRL_5.setText("InhA_M")
        self.mark_CRL_6.setText("PAPPA_M")
        self.mark_CRL_7.setText("NT_E")
        self.mark_CRL_8.setText("AFP_E")
        self.mark_CRL_9.setText("tbhCG_E")
        self.mark_CRL_10.setText("fbhCG_E")
        self.mark_CRL_11.setText("uE3_E")
        self.mark_CRL_12.setText("InhA_E")
        self.mark_CRL_13.setText("PAPPA_E")

        # IVF孕周类型标记物设置
        self.mark_IVF_1.setText("APF_M")
        self.mark_IVF_2.setText("tbhCG_M")
        self.mark_IVF_3.setText("fbhCG_M")
        self.mark_IVF_4.setText("uE3_M")
        self.mark_IVF_5.setText("InhA_M")
        self.mark_IVF_6.setText("PAPPA_M")
        self.mark_IVF_7.setText("NT_E")
        self.mark_IVF_8.setText("AFP_E")
        self.mark_IVF_9.setText("tbhCG_E")
        self.mark_IVF_10.setText("fbhCG_E")
        self.mark_IVF_11.setText("uE3_E")
        self.mark_IVF_12.setText("InhA_E")
        self.mark_IVF_13.setText("PAPPA_E")

        # BC孕周类型标记物设置
        self.mark_BC_1.setText("APF_M")
        self.mark_BC_2.setText("tbhCG_M")
        self.mark_BC_3.setText("fbhCG_M")
        self.mark_BC_4.setText("uE3_M")
        self.mark_BC_5.setText("InhA_M")
        self.mark_BC_6.setText("PAPPA_M")
        self.mark_BC_7.setText("NT_E")
        self.mark_BC_8.setText("AFP_E")
        self.mark_BC_9.setText("tbhCG_E")
        self.mark_BC_10.setText("fbhCG_E")
        self.mark_BC_11.setText("uE3_E")
        self.mark_BC_12.setText("InhA_E")
        self.mark_BC_13.setText("PAPPA_E")

    # 中位数表格标题设置
    def median_table_title(self):
        self.table_title = QtWidgets.QLabel(self)
        self.table_title.setGeometry(QtCore.QRect(600, 90, 500, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.table_title.setFont(font)
        self.table_title.setObjectName("table_title")

    #LMP孕周类型的标记物大小位置设置
    def test_item_LMP_setting(self):
        self.verticalLayoutWidget_LMP_2 = QtWidgets.QWidget(self.LMP_tab)
        self.verticalLayoutWidget_LMP_2.setGeometry(QtCore.QRect(260, 20, 180, 60))
        self.verticalLayoutWidget_LMP_2.setObjectName("verticalLayoutWidget_LMP_2")
        self.Layout_LMP_1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_LMP_2)
        self.Layout_LMP_1.setContentsMargins(0, 0, 0, 0)
        self.Layout_LMP_1.setObjectName("Layout_LMP_1")
        self.mark_LMP_1 = QtWidgets.QLabel(self.verticalLayoutWidget_LMP_2)
        self.mark_LMP_1.setObjectName("mark_LMP_1")
        self.Layout_LMP_1.addWidget(self.mark_LMP_1)
        self.version_LMP_1 = QtWidgets.QComboBox(self.verticalLayoutWidget_LMP_2)
        self.version_LMP_1.setObjectName("version_LMP_1")
        self.Layout_LMP_1.addWidget(self.version_LMP_1)
        self.verticalLayoutWidget_LMP_3 = QtWidgets.QWidget(self.LMP_tab)
        self.verticalLayoutWidget_LMP_3.setGeometry(QtCore.QRect(260, 80, 180, 60))
        self.verticalLayoutWidget_LMP_3.setObjectName("verticalLayoutWidget_LMP_3")
        self.Layout_LMP_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_LMP_3)
        self.Layout_LMP_2.setContentsMargins(0, 0, 0, 0)
        self.Layout_LMP_2.setObjectName("Layout_LMP_2")
        self.mark_LMP_2 = QtWidgets.QLabel(self.verticalLayoutWidget_LMP_3)
        self.mark_LMP_2.setObjectName("mark_LMP_2")
        self.Layout_LMP_2.addWidget(self.mark_LMP_2)
        self.version_LMP_2 = QtWidgets.QComboBox(self.verticalLayoutWidget_LMP_3)
        self.version_LMP_2.setObjectName("version_LMP_2")
        self.Layout_LMP_2.addWidget(self.version_LMP_2)
        self.verticalLayoutWidget_LMP_4 = QtWidgets.QWidget(self.LMP_tab)
        self.verticalLayoutWidget_LMP_4.setGeometry(QtCore.QRect(260, 140, 180, 60))
        self.verticalLayoutWidget_LMP_4.setObjectName("verticalLayoutWidget_LMP_4")
        self.Layout_LMP_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_LMP_4)
        self.Layout_LMP_3.setContentsMargins(0, 0, 0, 0)
        self.Layout_LMP_3.setObjectName("Layout_LMP_3")
        self.mark_LMP_3 = QtWidgets.QLabel(self.verticalLayoutWidget_LMP_4)
        self.mark_LMP_3.setObjectName("mark_LMP_3")
        self.Layout_LMP_3.addWidget(self.mark_LMP_3)
        self.version_LMP_3 = QtWidgets.QComboBox(self.verticalLayoutWidget_LMP_4)
        self.version_LMP_3.setObjectName("version_LMP_3")
        self.Layout_LMP_3.addWidget(self.version_LMP_3)
        self.verticalLayoutWidget_LMP_5 = QtWidgets.QWidget(self.LMP_tab)
        self.verticalLayoutWidget_LMP_5.setGeometry(QtCore.QRect(260, 200, 180, 60))
        self.verticalLayoutWidget_LMP_5.setObjectName("verticalLayoutWidget_LMP_5")
        self.Layout_LMP_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_LMP_5)
        self.Layout_LMP_4.setContentsMargins(0, 0, 0, 0)
        self.Layout_LMP_4.setObjectName("Layout_LMP_4")
        self.mark_LMP_4 = QtWidgets.QLabel(self.verticalLayoutWidget_LMP_5)
        self.mark_LMP_4.setObjectName("mark_LMP_4")
        self.Layout_LMP_4.addWidget(self.mark_LMP_4)
        self.version_LMP_4 = QtWidgets.QComboBox(self.verticalLayoutWidget_LMP_5)
        self.version_LMP_4.setObjectName("version_LMP_4")
        self.Layout_LMP_4.addWidget(self.version_LMP_4)
        self.verticalLayoutWidget_LMP_6 = QtWidgets.QWidget(self.LMP_tab)
        self.verticalLayoutWidget_LMP_6.setGeometry(QtCore.QRect(260, 260, 180, 60))
        self.verticalLayoutWidget_LMP_6.setObjectName("verticalLayoutWidget_LMP_6")
        self.Layout_LMP_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_LMP_6)
        self.Layout_LMP_5.setContentsMargins(0, 0, 0, 0)
        self.Layout_LMP_5.setObjectName("Layout_LMP_5")
        self.mark_LMP_5 = QtWidgets.QLabel(self.verticalLayoutWidget_LMP_6)
        self.mark_LMP_5.setObjectName("mark_LMP_5")
        self.Layout_LMP_5.addWidget(self.mark_LMP_5)
        self.version_LMP_5 = QtWidgets.QComboBox(self.verticalLayoutWidget_LMP_6)
        self.version_LMP_5.setObjectName("version_LMP_5")
        self.Layout_LMP_5.addWidget(self.version_LMP_5)
        self.verticalLayoutWidget_LMP_7 = QtWidgets.QWidget(self.LMP_tab)
        self.verticalLayoutWidget_LMP_7.setGeometry(QtCore.QRect(260, 320, 180, 60))
        self.verticalLayoutWidget_LMP_7.setObjectName("verticalLayoutWidget_LMP_7")
        self.Layout_LMP_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_LMP_7)
        self.Layout_LMP_6.setContentsMargins(0, 0, 0, 0)
        self.Layout_LMP_6.setObjectName("Layout_LMP_6")
        self.mark_LMP_6 = QtWidgets.QLabel(self.verticalLayoutWidget_LMP_7)
        self.mark_LMP_6.setObjectName("mark_LMP_6")
        self.Layout_LMP_6.addWidget(self.mark_LMP_6)
        self.version_LMP_6 = QtWidgets.QComboBox(self.verticalLayoutWidget_LMP_7)
        self.version_LMP_6.setObjectName("version_LMP_6")
        self.Layout_LMP_6.addWidget(self.version_LMP_6)
        self.verticalLayoutWidget_LMP_8 = QtWidgets.QWidget(self.LMP_tab)
        self.verticalLayoutWidget_LMP_8.setGeometry(QtCore.QRect(30, 380, 180, 60))
        self.verticalLayoutWidget_LMP_8.setObjectName("verticalLayoutWidget_LMP_8")
        self.Layout_LMP_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_LMP_8)
        self.Layout_LMP_7.setContentsMargins(0, 0, 0, 0)
        self.Layout_LMP_7.setObjectName("Layout_LMP_7")
        self.mark_LMP_7 = QtWidgets.QLabel(self.verticalLayoutWidget_LMP_8)
        self.mark_LMP_7.setObjectName("mark_LMP_7")
        self.Layout_LMP_7.addWidget(self.mark_LMP_7)
        self.version_LMP_7 = QtWidgets.QComboBox(self.verticalLayoutWidget_LMP_8)
        self.version_LMP_7.setObjectName("version_LMP_7")
        self.Layout_LMP_7.addWidget(self.version_LMP_7)
        self.verticalLayoutWidget_LMP_9 = QtWidgets.QWidget(self.LMP_tab)
        self.verticalLayoutWidget_LMP_9.setGeometry(QtCore.QRect(30, 20, 180, 60))
        self.verticalLayoutWidget_LMP_9.setObjectName("verticalLayoutWidget_LMP_9")
        self.Layout_LMP_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_LMP_9)
        self.Layout_LMP_8.setContentsMargins(0, 0, 0, 0)
        self.Layout_LMP_8.setObjectName("Layout_LMP_8")
        self.mark_LMP_8 = QtWidgets.QLabel(self.verticalLayoutWidget_LMP_9)
        self.mark_LMP_8.setObjectName("mark_LMP_8")
        self.Layout_LMP_8.addWidget(self.mark_LMP_8)
        self.version_LMP_8 = QtWidgets.QComboBox(self.verticalLayoutWidget_LMP_9)
        self.version_LMP_8.setObjectName("version_LMP_8")
        self.Layout_LMP_8.addWidget(self.version_LMP_8)
        self.verticalLayoutWidget_LMP_10 = QtWidgets.QWidget(self.LMP_tab)
        self.verticalLayoutWidget_LMP_10.setGeometry(QtCore.QRect(30, 80, 180, 60))
        self.verticalLayoutWidget_LMP_10.setObjectName("verticalLayoutWidget_LMP_10")
        self.Layout_LMP_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_LMP_10)
        self.Layout_LMP_9.setContentsMargins(0, 0, 0, 0)
        self.Layout_LMP_9.setObjectName("Layout_LMP_9")
        self.mark_LMP_9 = QtWidgets.QLabel(self.verticalLayoutWidget_LMP_10)
        self.mark_LMP_9.setObjectName("mark_LMP_9")
        self.Layout_LMP_9.addWidget(self.mark_LMP_9)
        self.version_LMP_9 = QtWidgets.QComboBox(self.verticalLayoutWidget_LMP_10)
        self.version_LMP_9.setObjectName("version_LMP_9")
        self.Layout_LMP_9.addWidget(self.version_LMP_9)
        self.verticalLayoutWidget_LMP_11 = QtWidgets.QWidget(self.LMP_tab)
        self.verticalLayoutWidget_LMP_11.setGeometry(QtCore.QRect(30, 140, 180, 60))
        self.verticalLayoutWidget_LMP_11.setObjectName("verticalLayoutWidget_LMP_11")
        self.Layout_LMP_10 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_LMP_11)
        self.Layout_LMP_10.setContentsMargins(0, 0, 0, 0)
        self.Layout_LMP_10.setObjectName("Layout_LMP_10")
        self.mark_LMP_10 = QtWidgets.QLabel(self.verticalLayoutWidget_LMP_11)
        self.mark_LMP_10.setObjectName("mark_LMP_10")
        self.Layout_LMP_10.addWidget(self.mark_LMP_10)
        self.version_LMP_10 = QtWidgets.QComboBox(self.verticalLayoutWidget_LMP_11)
        self.version_LMP_10.setObjectName("version_LMP_10")
        self.Layout_LMP_10.addWidget(self.version_LMP_10)
        self.verticalLayoutWidget_LMP_12 = QtWidgets.QWidget(self.LMP_tab)
        self.verticalLayoutWidget_LMP_12.setGeometry(QtCore.QRect(30, 200, 180, 60))
        self.verticalLayoutWidget_LMP_12.setObjectName("verticalLayoutWidget_LMP_12")
        self.Layout_LMP_11 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_LMP_12)
        self.Layout_LMP_11.setContentsMargins(0, 0, 0, 0)
        self.Layout_LMP_11.setObjectName("Layout_LMP_11")
        self.mark_LMP_11 = QtWidgets.QLabel(self.verticalLayoutWidget_LMP_12)
        self.mark_LMP_11.setObjectName("mark_LMP_11")
        self.Layout_LMP_11.addWidget(self.mark_LMP_11)
        self.version_LMP_11 = QtWidgets.QComboBox(self.verticalLayoutWidget_LMP_12)
        self.version_LMP_11.setObjectName("version_LMP_11")
        self.Layout_LMP_11.addWidget(self.version_LMP_11)
        self.verticalLayoutWidget_LMP_13 = QtWidgets.QWidget(self.LMP_tab)
        self.verticalLayoutWidget_LMP_13.setGeometry(QtCore.QRect(30, 260, 180, 60))
        self.verticalLayoutWidget_LMP_13.setObjectName("verticalLayoutWidget_LMP_13")
        self.Layout_LMP_12 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_LMP_13)
        self.Layout_LMP_12.setContentsMargins(0, 0, 0, 0)
        self.Layout_LMP_12.setObjectName("Layout_LMP_12")
        self.mark_LMP_12 = QtWidgets.QLabel(self.verticalLayoutWidget_LMP_13)
        self.mark_LMP_12.setObjectName("mark_LMP_12")
        self.Layout_LMP_12.addWidget(self.mark_LMP_12)
        self.version_LMP_12 = QtWidgets.QComboBox(self.verticalLayoutWidget_LMP_13)
        self.version_LMP_12.setObjectName("version_LMP_12")
        self.Layout_LMP_12.addWidget(self.version_LMP_12)
        self.verticalLayoutWidget_LMP_14 = QtWidgets.QWidget(self.LMP_tab)
        self.verticalLayoutWidget_LMP_14.setGeometry(QtCore.QRect(30, 320, 180, 60))
        self.verticalLayoutWidget_LMP_14.setObjectName("verticalLayoutWidget_LMP_14")
        self.Layout_LMP_13 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_LMP_14)
        self.Layout_LMP_13.setContentsMargins(0, 0, 0, 0)
        self.Layout_LMP_13.setObjectName("Layout_LMP_13")
        self.mark_LMP_13 = QtWidgets.QLabel(self.verticalLayoutWidget_LMP_14)
        self.mark_LMP_13.setObjectName("mark_LMP_13")
        self.Layout_LMP_13.addWidget(self.mark_LMP_13)
        self.version_LMP_13 = QtWidgets.QComboBox(self.verticalLayoutWidget_LMP_14)
        self.version_LMP_13.setObjectName("version_LMP_13")
        self.Layout_LMP_13.addWidget(self.version_LMP_13)

        # 下拉框内容更改时
        self.version_LMP_1.activated.connect(lambda: self.choose_item(self.version_LMP_1.currentText(), 1, 1))
        self.version_LMP_2.activated.connect(lambda: self.choose_item(self.version_LMP_2.currentText(), 2, 1))
        self.version_LMP_3.activated.connect(lambda: self.choose_item(self.version_LMP_3.currentText(), 3, 1))
        self.version_LMP_4.activated.connect(lambda: self.choose_item(self.version_LMP_4.currentText(), 4, 1))
        self.version_LMP_5.activated.connect(lambda: self.choose_item(self.version_LMP_5.currentText(), 5, 1))
        self.version_LMP_6.activated.connect(lambda: self.choose_item(self.version_LMP_6.currentText(), 6, 1))
        self.version_LMP_7.activated.connect(lambda: self.choose_item(self.version_LMP_7.currentText(), 7, 1))
        self.version_LMP_8.activated.connect(lambda: self.choose_item(self.version_LMP_8.currentText(), 8, 1))
        self.version_LMP_9.activated.connect(lambda: self.choose_item(self.version_LMP_9.currentText(), 9, 1))
        self.version_LMP_10.activated.connect(lambda: self.choose_item(self.version_LMP_10.currentText(), 10, 1))
        self.version_LMP_11.activated.connect(lambda: self.choose_item(self.version_LMP_11.currentText(), 11, 1))
        self.version_LMP_12.activated.connect(lambda: self.choose_item(self.version_LMP_12.currentText(), 12, 1))
        self.version_LMP_13.activated.connect(lambda: self.choose_item(self.version_LMP_13.currentText(), 13, 1))

    # BPD孕周类型的标记物大小位置设置
    def test_item_BPD_setting(self):
        self.verticalLayoutWidget_BPD_2 = QtWidgets.QWidget(self.BPD_tab)
        self.verticalLayoutWidget_BPD_2.setGeometry(QtCore.QRect(260, 20, 180, 60))
        self.verticalLayoutWidget_BPD_2.setObjectName("verticalLayoutWidget_BPD_2")
        self.Layout_BPD_1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_BPD_2)
        self.Layout_BPD_1.setContentsMargins(0, 0, 0, 0)
        self.Layout_BPD_1.setObjectName("Layout_BPD_1")
        self.mark_BPD_1 = QtWidgets.QLabel(self.verticalLayoutWidget_BPD_2)
        self.mark_BPD_1.setObjectName("mark_BPD_1")
        self.Layout_BPD_1.addWidget(self.mark_BPD_1)
        self.version_BPD_1 = QtWidgets.QComboBox(self.verticalLayoutWidget_BPD_2)
        self.version_BPD_1.setObjectName("version_BPD_1")
        self.Layout_BPD_1.addWidget(self.version_BPD_1)
        self.verticalLayoutWidget_BPD_3 = QtWidgets.QWidget(self.BPD_tab)
        self.verticalLayoutWidget_BPD_3.setGeometry(QtCore.QRect(260, 80, 180, 60))
        self.verticalLayoutWidget_BPD_3.setObjectName("verticalLayoutWidget_BPD_3")
        self.Layout_BPD_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_BPD_3)
        self.Layout_BPD_2.setContentsMargins(0, 0, 0, 0)
        self.Layout_BPD_2.setObjectName("Layout_BPD_2")
        self.mark_BPD_2 = QtWidgets.QLabel(self.verticalLayoutWidget_BPD_3)
        self.mark_BPD_2.setObjectName("mark_BPD_2")
        self.Layout_BPD_2.addWidget(self.mark_BPD_2)
        self.version_BPD_2 = QtWidgets.QComboBox(self.verticalLayoutWidget_BPD_3)
        self.version_BPD_2.setObjectName("version_BPD_2")
        self.Layout_BPD_2.addWidget(self.version_BPD_2)
        self.verticalLayoutWidget_BPD_4 = QtWidgets.QWidget(self.BPD_tab)
        self.verticalLayoutWidget_BPD_4.setGeometry(QtCore.QRect(260, 140, 180, 60))
        self.verticalLayoutWidget_BPD_4.setObjectName("verticalLayoutWidget_BPD_4")
        self.Layout_BPD_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_BPD_4)
        self.Layout_BPD_3.setContentsMargins(0, 0, 0, 0)
        self.Layout_BPD_3.setObjectName("Layout_BPD_3")
        self.mark_BPD_3 = QtWidgets.QLabel(self.verticalLayoutWidget_BPD_4)
        self.mark_BPD_3.setObjectName("mark_BPD_3")
        self.Layout_BPD_3.addWidget(self.mark_BPD_3)
        self.version_BPD_3 = QtWidgets.QComboBox(self.verticalLayoutWidget_BPD_4)
        self.version_BPD_3.setObjectName("version_BPD_3")
        self.Layout_BPD_3.addWidget(self.version_BPD_3)
        self.verticalLayoutWidget_BPD_5 = QtWidgets.QWidget(self.BPD_tab)
        self.verticalLayoutWidget_BPD_5.setGeometry(QtCore.QRect(260, 200, 180, 60))
        self.verticalLayoutWidget_BPD_5.setObjectName("verticalLayoutWidget_BPD_5")
        self.Layout_BPD_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_BPD_5)
        self.Layout_BPD_4.setContentsMargins(0, 0, 0, 0)
        self.Layout_BPD_4.setObjectName("Layout_BPD_4")
        self.mark_BPD_4 = QtWidgets.QLabel(self.verticalLayoutWidget_BPD_5)
        self.mark_BPD_4.setObjectName("mark_BPD_4")
        self.Layout_BPD_4.addWidget(self.mark_BPD_4)
        self.version_BPD_4 = QtWidgets.QComboBox(self.verticalLayoutWidget_BPD_5)
        self.version_BPD_4.setObjectName("version_BPD_4")
        self.Layout_BPD_4.addWidget(self.version_BPD_4)
        self.verticalLayoutWidget_BPD_6 = QtWidgets.QWidget(self.BPD_tab)
        self.verticalLayoutWidget_BPD_6.setGeometry(QtCore.QRect(260, 260, 180, 60))
        self.verticalLayoutWidget_BPD_6.setObjectName("verticalLayoutWidget_BPD_6")
        self.Layout_BPD_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_BPD_6)
        self.Layout_BPD_5.setContentsMargins(0, 0, 0, 0)
        self.Layout_BPD_5.setObjectName("Layout_BPD_5")
        self.mark_BPD_5 = QtWidgets.QLabel(self.verticalLayoutWidget_BPD_6)
        self.mark_BPD_5.setObjectName("mark_BPD_5")
        self.Layout_BPD_5.addWidget(self.mark_BPD_5)
        self.version_BPD_5 = QtWidgets.QComboBox(self.verticalLayoutWidget_BPD_6)
        self.version_BPD_5.setObjectName("version_BPD_5")
        self.Layout_BPD_5.addWidget(self.version_BPD_5)
        self.verticalLayoutWidget_BPD_7 = QtWidgets.QWidget(self.BPD_tab)
        self.verticalLayoutWidget_BPD_7.setGeometry(QtCore.QRect(260, 320, 180, 60))
        self.verticalLayoutWidget_BPD_7.setObjectName("verticalLayoutWidget_BPD_7")
        self.Layout_BPD_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_BPD_7)
        self.Layout_BPD_6.setContentsMargins(0, 0, 0, 0)
        self.Layout_BPD_6.setObjectName("Layout_BPD_6")
        self.mark_BPD_6 = QtWidgets.QLabel(self.verticalLayoutWidget_BPD_7)
        self.mark_BPD_6.setObjectName("mark_BPD_6")
        self.Layout_BPD_6.addWidget(self.mark_BPD_6)
        self.version_BPD_6 = QtWidgets.QComboBox(self.verticalLayoutWidget_BPD_7)
        self.version_BPD_6.setObjectName("version_BPD_6")
        self.Layout_BPD_6.addWidget(self.version_BPD_6)
        self.verticalLayoutWidget_BPD_8 = QtWidgets.QWidget(self.BPD_tab)
        self.verticalLayoutWidget_BPD_8.setGeometry(QtCore.QRect(30, 380, 180, 60))
        self.verticalLayoutWidget_BPD_8.setObjectName("verticalLayoutWidget_BPD_8")
        self.Layout_BPD_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_BPD_8)
        self.Layout_BPD_7.setContentsMargins(0, 0, 0, 0)
        self.Layout_BPD_7.setObjectName("Layout_BPD_7")
        self.mark_BPD_7 = QtWidgets.QLabel(self.verticalLayoutWidget_BPD_8)
        self.mark_BPD_7.setObjectName("mark_BPD_7")
        self.Layout_BPD_7.addWidget(self.mark_BPD_7)
        self.version_BPD_7 = QtWidgets.QComboBox(self.verticalLayoutWidget_BPD_8)
        self.version_BPD_7.setObjectName("version_BPD_7")
        self.Layout_BPD_7.addWidget(self.version_BPD_7)
        self.verticalLayoutWidget_BPD_9 = QtWidgets.QWidget(self.BPD_tab)
        self.verticalLayoutWidget_BPD_9.setGeometry(QtCore.QRect(30, 20, 180, 60))
        self.verticalLayoutWidget_BPD_9.setObjectName("verticalLayoutWidget_BPD_9")
        self.Layout_BPD_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_BPD_9)
        self.Layout_BPD_8.setContentsMargins(0, 0, 0, 0)
        self.Layout_BPD_8.setObjectName("Layout_BPD_8")
        self.mark_BPD_8 = QtWidgets.QLabel(self.verticalLayoutWidget_BPD_9)
        self.mark_BPD_8.setObjectName("mark_BPD_8")
        self.Layout_BPD_8.addWidget(self.mark_BPD_8)
        self.version_BPD_8 = QtWidgets.QComboBox(self.verticalLayoutWidget_BPD_9)
        self.version_BPD_8.setObjectName("version_BPD_8")
        self.Layout_BPD_8.addWidget(self.version_BPD_8)
        self.verticalLayoutWidget_BPD_10 = QtWidgets.QWidget(self.BPD_tab)
        self.verticalLayoutWidget_BPD_10.setGeometry(QtCore.QRect(30, 80, 180, 60))
        self.verticalLayoutWidget_BPD_10.setObjectName("verticalLayoutWidget_BPD_10")
        self.Layout_BPD_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_BPD_10)
        self.Layout_BPD_9.setContentsMargins(0, 0, 0, 0)
        self.Layout_BPD_9.setObjectName("Layout_BPD_9")
        self.mark_BPD_9 = QtWidgets.QLabel(self.verticalLayoutWidget_BPD_10)
        self.mark_BPD_9.setObjectName("mark_BPD_9")
        self.Layout_BPD_9.addWidget(self.mark_BPD_9)
        self.version_BPD_9 = QtWidgets.QComboBox(self.verticalLayoutWidget_BPD_10)
        self.version_BPD_9.setObjectName("version_BPD_9")
        self.Layout_BPD_9.addWidget(self.version_BPD_9)
        self.verticalLayoutWidget_BPD_11 = QtWidgets.QWidget(self.BPD_tab)
        self.verticalLayoutWidget_BPD_11.setGeometry(QtCore.QRect(30, 140, 180, 60))
        self.verticalLayoutWidget_BPD_11.setObjectName("verticalLayoutWidget_BPD_11")
        self.Layout_BPD_10 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_BPD_11)
        self.Layout_BPD_10.setContentsMargins(0, 0, 0, 0)
        self.Layout_BPD_10.setObjectName("Layout_BPD_10")
        self.mark_BPD_10 = QtWidgets.QLabel(self.verticalLayoutWidget_BPD_11)
        self.mark_BPD_10.setObjectName("mark_BPD_10")
        self.Layout_BPD_10.addWidget(self.mark_BPD_10)
        self.version_BPD_10 = QtWidgets.QComboBox(self.verticalLayoutWidget_BPD_11)
        self.version_BPD_10.setObjectName("version_BPD_10")
        self.Layout_BPD_10.addWidget(self.version_BPD_10)
        self.verticalLayoutWidget_BPD_12 = QtWidgets.QWidget(self.BPD_tab)
        self.verticalLayoutWidget_BPD_12.setGeometry(QtCore.QRect(30, 200, 180, 60))
        self.verticalLayoutWidget_BPD_12.setObjectName("verticalLayoutWidget_BPD_12")
        self.Layout_BPD_11 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_BPD_12)
        self.Layout_BPD_11.setContentsMargins(0, 0, 0, 0)
        self.Layout_BPD_11.setObjectName("Layout_BPD_11")
        self.mark_BPD_11 = QtWidgets.QLabel(self.verticalLayoutWidget_BPD_12)
        self.mark_BPD_11.setObjectName("mark_BPD_11")
        self.Layout_BPD_11.addWidget(self.mark_BPD_11)
        self.version_BPD_11 = QtWidgets.QComboBox(self.verticalLayoutWidget_BPD_12)
        self.version_BPD_11.setObjectName("version_BPD_11")
        self.Layout_BPD_11.addWidget(self.version_BPD_11)
        self.verticalLayoutWidget_BPD_13 = QtWidgets.QWidget(self.BPD_tab)
        self.verticalLayoutWidget_BPD_13.setGeometry(QtCore.QRect(30, 260, 180, 60))
        self.verticalLayoutWidget_BPD_13.setObjectName("verticalLayoutWidget_BPD_13")
        self.Layout_BPD_12 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_BPD_13)
        self.Layout_BPD_12.setContentsMargins(0, 0, 0, 0)
        self.Layout_BPD_12.setObjectName("Layout_BPD_12")
        self.mark_BPD_12 = QtWidgets.QLabel(self.verticalLayoutWidget_BPD_13)
        self.mark_BPD_12.setObjectName("mark_BPD_12")
        self.Layout_BPD_12.addWidget(self.mark_BPD_12)
        self.version_BPD_12 = QtWidgets.QComboBox(self.verticalLayoutWidget_BPD_13)
        self.version_BPD_12.setObjectName("version_BPD_12")
        self.Layout_BPD_12.addWidget(self.version_BPD_12)
        self.verticalLayoutWidget_BPD_14 = QtWidgets.QWidget(self.BPD_tab)
        self.verticalLayoutWidget_BPD_14.setGeometry(QtCore.QRect(30, 320, 180, 60))
        self.verticalLayoutWidget_BPD_14.setObjectName("verticalLayoutWidget_BPD_14")
        self.Layout_BPD_13 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_BPD_14)
        self.Layout_BPD_13.setContentsMargins(0, 0, 0, 0)
        self.Layout_BPD_13.setObjectName("Layout_BPD_13")
        self.mark_BPD_13 = QtWidgets.QLabel(self.verticalLayoutWidget_BPD_14)
        self.mark_BPD_13.setObjectName("mark_BPD_13")
        self.Layout_BPD_13.addWidget(self.mark_BPD_13)
        self.version_BPD_13 = QtWidgets.QComboBox(self.verticalLayoutWidget_BPD_14)
        self.version_BPD_13.setObjectName("version_BPD_13")
        self.Layout_BPD_13.addWidget(self.version_BPD_13)

        # 下拉框内容更改时
        self.version_BPD_1.activated.connect(lambda: self.choose_item(self.version_BPD_1.currentText(), 1, 2))
        self.version_BPD_2.activated.connect(lambda: self.choose_item(self.version_BPD_2.currentText(), 2, 2))
        self.version_BPD_3.activated.connect(lambda: self.choose_item(self.version_BPD_3.currentText(), 3, 2))
        self.version_BPD_4.activated.connect(lambda: self.choose_item(self.version_BPD_4.currentText(), 4, 2))
        self.version_BPD_5.activated.connect(lambda: self.choose_item(self.version_BPD_5.currentText(), 5, 2))
        self.version_BPD_6.activated.connect(lambda: self.choose_item(self.version_BPD_6.currentText(), 6, 2))
        self.version_BPD_7.activated.connect(lambda: self.choose_item(self.version_BPD_7.currentText(), 7, 2))
        self.version_BPD_8.activated.connect(lambda: self.choose_item(self.version_BPD_8.currentText(), 8, 2))
        self.version_BPD_9.activated.connect(lambda: self.choose_item(self.version_BPD_9.currentText(), 9, 2))
        self.version_BPD_10.activated.connect(lambda: self.choose_item(self.version_BPD_10.currentText(), 10, 2))
        self.version_BPD_11.activated.connect(lambda: self.choose_item(self.version_BPD_11.currentText(), 11, 2))
        self.version_BPD_12.activated.connect(lambda: self.choose_item(self.version_BPD_12.currentText(), 12, 2))
        self.version_BPD_13.activated.connect(lambda: self.choose_item(self.version_BPD_13.currentText(), 13, 2))

    # CRL孕周类型的标记物大小位置设置
    def test_item_CRL_setting(self):
        self.verticalLayoutWidget_CRL_2 = QtWidgets.QWidget(self.CRL_tab)
        self.verticalLayoutWidget_CRL_2.setGeometry(QtCore.QRect(260, 20, 180, 60))
        self.verticalLayoutWidget_CRL_2.setObjectName("verticalLayoutWidget_CRL_2")
        self.Layout_CRL_1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_CRL_2)
        self.Layout_CRL_1.setContentsMargins(0, 0, 0, 0)
        self.Layout_CRL_1.setObjectName("Layout_CRL_1")
        self.mark_CRL_1 = QtWidgets.QLabel(self.verticalLayoutWidget_CRL_2)
        self.mark_CRL_1.setObjectName("mark_CRL_1")
        self.Layout_CRL_1.addWidget(self.mark_CRL_1)
        self.version_CRL_1 = QtWidgets.QComboBox(self.verticalLayoutWidget_CRL_2)
        self.version_CRL_1.setObjectName("version_CRL_1")
        self.Layout_CRL_1.addWidget(self.version_CRL_1)
        self.verticalLayoutWidget_CRL_3 = QtWidgets.QWidget(self.CRL_tab)
        self.verticalLayoutWidget_CRL_3.setGeometry(QtCore.QRect(260, 80, 180, 60))
        self.verticalLayoutWidget_CRL_3.setObjectName("verticalLayoutWidget_CRL_3")
        self.Layout_CRL_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_CRL_3)
        self.Layout_CRL_2.setContentsMargins(0, 0, 0, 0)
        self.Layout_CRL_2.setObjectName("Layout_CRL_2")
        self.mark_CRL_2 = QtWidgets.QLabel(self.verticalLayoutWidget_CRL_3)
        self.mark_CRL_2.setObjectName("mark_CRL_2")
        self.Layout_CRL_2.addWidget(self.mark_CRL_2)
        self.version_CRL_2 = QtWidgets.QComboBox(self.verticalLayoutWidget_CRL_3)
        self.version_CRL_2.setObjectName("version_CRL_2")
        self.Layout_CRL_2.addWidget(self.version_CRL_2)
        self.verticalLayoutWidget_CRL_4 = QtWidgets.QWidget(self.CRL_tab)
        self.verticalLayoutWidget_CRL_4.setGeometry(QtCore.QRect(260, 140, 180, 60))
        self.verticalLayoutWidget_CRL_4.setObjectName("verticalLayoutWidget_CRL_4")
        self.Layout_CRL_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_CRL_4)
        self.Layout_CRL_3.setContentsMargins(0, 0, 0, 0)
        self.Layout_CRL_3.setObjectName("Layout_CRL_3")
        self.mark_CRL_3 = QtWidgets.QLabel(self.verticalLayoutWidget_CRL_4)
        self.mark_CRL_3.setObjectName("mark_CRL_3")
        self.Layout_CRL_3.addWidget(self.mark_CRL_3)
        self.version_CRL_3 = QtWidgets.QComboBox(self.verticalLayoutWidget_CRL_4)
        self.version_CRL_3.setObjectName("version_CRL_3")
        self.Layout_CRL_3.addWidget(self.version_CRL_3)
        self.verticalLayoutWidget_CRL_5 = QtWidgets.QWidget(self.CRL_tab)
        self.verticalLayoutWidget_CRL_5.setGeometry(QtCore.QRect(260, 200, 180, 60))
        self.verticalLayoutWidget_CRL_5.setObjectName("verticalLayoutWidget_CRL_5")
        self.Layout_CRL_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_CRL_5)
        self.Layout_CRL_4.setContentsMargins(0, 0, 0, 0)
        self.Layout_CRL_4.setObjectName("Layout_CRL_4")
        self.mark_CRL_4 = QtWidgets.QLabel(self.verticalLayoutWidget_CRL_5)
        self.mark_CRL_4.setObjectName("mark_CRL_4")
        self.Layout_CRL_4.addWidget(self.mark_CRL_4)
        self.version_CRL_4 = QtWidgets.QComboBox(self.verticalLayoutWidget_CRL_5)
        self.version_CRL_4.setObjectName("version_CRL_4")
        self.Layout_CRL_4.addWidget(self.version_CRL_4)
        self.verticalLayoutWidget_CRL_6 = QtWidgets.QWidget(self.CRL_tab)
        self.verticalLayoutWidget_CRL_6.setGeometry(QtCore.QRect(260, 260, 180, 60))
        self.verticalLayoutWidget_CRL_6.setObjectName("verticalLayoutWidget_CRL_6")
        self.Layout_CRL_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_CRL_6)
        self.Layout_CRL_5.setContentsMargins(0, 0, 0, 0)
        self.Layout_CRL_5.setObjectName("Layout_CRL_5")
        self.mark_CRL_5 = QtWidgets.QLabel(self.verticalLayoutWidget_CRL_6)
        self.mark_CRL_5.setObjectName("mark_CRL_5")
        self.Layout_CRL_5.addWidget(self.mark_CRL_5)
        self.version_CRL_5 = QtWidgets.QComboBox(self.verticalLayoutWidget_CRL_6)
        self.version_CRL_5.setObjectName("version_CRL_5")
        self.Layout_CRL_5.addWidget(self.version_CRL_5)
        self.verticalLayoutWidget_CRL_7 = QtWidgets.QWidget(self.CRL_tab)
        self.verticalLayoutWidget_CRL_7.setGeometry(QtCore.QRect(260, 320, 180, 60))
        self.verticalLayoutWidget_CRL_7.setObjectName("verticalLayoutWidget_CRL_7")
        self.Layout_CRL_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_CRL_7)
        self.Layout_CRL_6.setContentsMargins(0, 0, 0, 0)
        self.Layout_CRL_6.setObjectName("Layout_CRL_6")
        self.mark_CRL_6 = QtWidgets.QLabel(self.verticalLayoutWidget_CRL_7)
        self.mark_CRL_6.setObjectName("mark_CRL_6")
        self.Layout_CRL_6.addWidget(self.mark_CRL_6)
        self.version_CRL_6 = QtWidgets.QComboBox(self.verticalLayoutWidget_CRL_7)
        self.version_CRL_6.setObjectName("version_CRL_6")
        self.Layout_CRL_6.addWidget(self.version_CRL_6)
        self.verticalLayoutWidget_CRL_8 = QtWidgets.QWidget(self.CRL_tab)
        self.verticalLayoutWidget_CRL_8.setGeometry(QtCore.QRect(30, 380, 180, 60))
        self.verticalLayoutWidget_CRL_8.setObjectName("verticalLayoutWidget_CRL_8")
        self.Layout_CRL_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_CRL_8)
        self.Layout_CRL_7.setContentsMargins(0, 0, 0, 0)
        self.Layout_CRL_7.setObjectName("Layout_CRL_7")
        self.mark_CRL_7 = QtWidgets.QLabel(self.verticalLayoutWidget_CRL_8)
        self.mark_CRL_7.setObjectName("mark_CRL_7")
        self.Layout_CRL_7.addWidget(self.mark_CRL_7)
        self.version_CRL_7 = QtWidgets.QComboBox(self.verticalLayoutWidget_CRL_8)
        self.version_CRL_7.setObjectName("version_CRL_7")
        self.Layout_CRL_7.addWidget(self.version_CRL_7)
        self.verticalLayoutWidget_CRL_9 = QtWidgets.QWidget(self.CRL_tab)
        self.verticalLayoutWidget_CRL_9.setGeometry(QtCore.QRect(30, 20, 180, 60))
        self.verticalLayoutWidget_CRL_9.setObjectName("verticalLayoutWidget_CRL_9")
        self.Layout_CRL_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_CRL_9)
        self.Layout_CRL_8.setContentsMargins(0, 0, 0, 0)
        self.Layout_CRL_8.setObjectName("Layout_CRL_8")
        self.mark_CRL_8 = QtWidgets.QLabel(self.verticalLayoutWidget_CRL_9)
        self.mark_CRL_8.setObjectName("mark_CRL_8")
        self.Layout_CRL_8.addWidget(self.mark_CRL_8)
        self.version_CRL_8 = QtWidgets.QComboBox(self.verticalLayoutWidget_CRL_9)
        self.version_CRL_8.setObjectName("version_CRL_8")
        self.Layout_CRL_8.addWidget(self.version_CRL_8)
        self.verticalLayoutWidget_CRL_10 = QtWidgets.QWidget(self.CRL_tab)
        self.verticalLayoutWidget_CRL_10.setGeometry(QtCore.QRect(30, 80, 180, 60))
        self.verticalLayoutWidget_CRL_10.setObjectName("verticalLayoutWidget_CRL_10")
        self.Layout_CRL_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_CRL_10)
        self.Layout_CRL_9.setContentsMargins(0, 0, 0, 0)
        self.Layout_CRL_9.setObjectName("Layout_CRL_9")
        self.mark_CRL_9 = QtWidgets.QLabel(self.verticalLayoutWidget_CRL_10)
        self.mark_CRL_9.setObjectName("mark_CRL_9")
        self.Layout_CRL_9.addWidget(self.mark_CRL_9)
        self.version_CRL_9 = QtWidgets.QComboBox(self.verticalLayoutWidget_CRL_10)
        self.version_CRL_9.setObjectName("version_CRL_9")
        self.Layout_CRL_9.addWidget(self.version_CRL_9)
        self.verticalLayoutWidget_CRL_11 = QtWidgets.QWidget(self.CRL_tab)
        self.verticalLayoutWidget_CRL_11.setGeometry(QtCore.QRect(30, 140, 180, 60))
        self.verticalLayoutWidget_CRL_11.setObjectName("verticalLayoutWidget_CRL_11")
        self.Layout_CRL_10 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_CRL_11)
        self.Layout_CRL_10.setContentsMargins(0, 0, 0, 0)
        self.Layout_CRL_10.setObjectName("Layout_CRL_10")
        self.mark_CRL_10 = QtWidgets.QLabel(self.verticalLayoutWidget_CRL_11)
        self.mark_CRL_10.setObjectName("mark_CRL_10")
        self.Layout_CRL_10.addWidget(self.mark_CRL_10)
        self.version_CRL_10 = QtWidgets.QComboBox(self.verticalLayoutWidget_CRL_11)
        self.version_CRL_10.setObjectName("version_CRL_10")
        self.Layout_CRL_10.addWidget(self.version_CRL_10)
        self.verticalLayoutWidget_CRL_12 = QtWidgets.QWidget(self.CRL_tab)
        self.verticalLayoutWidget_CRL_12.setGeometry(QtCore.QRect(30, 200, 180, 60))
        self.verticalLayoutWidget_CRL_12.setObjectName("verticalLayoutWidget_CRL_12")
        self.Layout_CRL_11 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_CRL_12)
        self.Layout_CRL_11.setContentsMargins(0, 0, 0, 0)
        self.Layout_CRL_11.setObjectName("Layout_CRL_11")
        self.mark_CRL_11 = QtWidgets.QLabel(self.verticalLayoutWidget_CRL_12)
        self.mark_CRL_11.setObjectName("mark_CRL_11")
        self.Layout_CRL_11.addWidget(self.mark_CRL_11)
        self.version_CRL_11 = QtWidgets.QComboBox(self.verticalLayoutWidget_CRL_12)
        self.version_CRL_11.setObjectName("version_CRL_11")
        self.Layout_CRL_11.addWidget(self.version_CRL_11)
        self.verticalLayoutWidget_CRL_13 = QtWidgets.QWidget(self.CRL_tab)
        self.verticalLayoutWidget_CRL_13.setGeometry(QtCore.QRect(30, 260, 180, 60))
        self.verticalLayoutWidget_CRL_13.setObjectName("verticalLayoutWidget_CRL_13")
        self.Layout_CRL_12 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_CRL_13)
        self.Layout_CRL_12.setContentsMargins(0, 0, 0, 0)
        self.Layout_CRL_12.setObjectName("Layout_CRL_12")
        self.mark_CRL_12 = QtWidgets.QLabel(self.verticalLayoutWidget_CRL_13)
        self.mark_CRL_12.setObjectName("mark_CRL_12")
        self.Layout_CRL_12.addWidget(self.mark_CRL_12)
        self.version_CRL_12 = QtWidgets.QComboBox(self.verticalLayoutWidget_CRL_13)
        self.version_CRL_12.setObjectName("version_CRL_12")
        self.Layout_CRL_12.addWidget(self.version_CRL_12)
        self.verticalLayoutWidget_CRL_14 = QtWidgets.QWidget(self.CRL_tab)
        self.verticalLayoutWidget_CRL_14.setGeometry(QtCore.QRect(30, 320, 180, 60))
        self.verticalLayoutWidget_CRL_14.setObjectName("verticalLayoutWidget_CRL_14")
        self.Layout_CRL_13 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_CRL_14)
        self.Layout_CRL_13.setContentsMargins(0, 0, 0, 0)
        self.Layout_CRL_13.setObjectName("Layout_CRL_13")
        self.mark_CRL_13 = QtWidgets.QLabel(self.verticalLayoutWidget_CRL_14)
        self.mark_CRL_13.setObjectName("mark_CRL_13")
        self.Layout_CRL_13.addWidget(self.mark_CRL_13)
        self.version_CRL_13 = QtWidgets.QComboBox(self.verticalLayoutWidget_CRL_14)
        self.version_CRL_13.setObjectName("version_CRL_13")
        self.Layout_CRL_13.addWidget(self.version_CRL_13)

        # 下拉框内容更改时
        self.version_CRL_1.activated.connect(lambda: self.choose_item(self.version_CRL_1.currentText(), 1, 3))
        self.version_CRL_2.activated.connect(lambda: self.choose_item(self.version_CRL_2.currentText(), 2, 3))
        self.version_CRL_3.activated.connect(lambda: self.choose_item(self.version_CRL_3.currentText(), 3, 3))
        self.version_CRL_4.activated.connect(lambda: self.choose_item(self.version_CRL_4.currentText(), 4, 3))
        self.version_CRL_5.activated.connect(lambda: self.choose_item(self.version_CRL_5.currentText(), 5, 3))
        self.version_CRL_6.activated.connect(lambda: self.choose_item(self.version_CRL_6.currentText(), 6, 3))
        self.version_CRL_7.activated.connect(lambda: self.choose_item(self.version_CRL_7.currentText(), 7, 3))
        self.version_CRL_8.activated.connect(lambda: self.choose_item(self.version_CRL_8.currentText(), 8, 3))
        self.version_CRL_9.activated.connect(lambda: self.choose_item(self.version_CRL_9.currentText(), 9, 3))
        self.version_CRL_10.activated.connect(lambda: self.choose_item(self.version_CRL_10.currentText(), 10, 3))
        self.version_CRL_11.activated.connect(lambda: self.choose_item(self.version_CRL_11.currentText(), 11, 3))
        self.version_CRL_12.activated.connect(lambda: self.choose_item(self.version_CRL_12.currentText(), 12, 3))
        self.version_CRL_13.activated.connect(lambda: self.choose_item(self.version_CRL_13.currentText(), 13, 3))

    # IVF孕周类型的标记物大小位置设置
    def test_item_IVF_setting(self):
        self.verticalLayoutWidget_IVF_2 = QtWidgets.QWidget(self.IVF_tab)
        self.verticalLayoutWidget_IVF_2.setGeometry(QtCore.QRect(260, 20, 180, 60))
        self.verticalLayoutWidget_IVF_2.setObjectName("verticalLayoutWidget_IVF_2")
        self.Layout_IVF_1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_IVF_2)
        self.Layout_IVF_1.setContentsMargins(0, 0, 0, 0)
        self.Layout_IVF_1.setObjectName("Layout_IVF_1")
        self.mark_IVF_1 = QtWidgets.QLabel(self.verticalLayoutWidget_IVF_2)
        self.mark_IVF_1.setObjectName("mark_IVF_1")
        self.Layout_IVF_1.addWidget(self.mark_IVF_1)
        self.version_IVF_1 = QtWidgets.QComboBox(self.verticalLayoutWidget_IVF_2)
        self.version_IVF_1.setObjectName("version_IVF_1")
        self.Layout_IVF_1.addWidget(self.version_IVF_1)
        self.verticalLayoutWidget_IVF_3 = QtWidgets.QWidget(self.IVF_tab)
        self.verticalLayoutWidget_IVF_3.setGeometry(QtCore.QRect(260, 80, 180, 60))
        self.verticalLayoutWidget_IVF_3.setObjectName("verticalLayoutWidget_IVF_3")
        self.Layout_IVF_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_IVF_3)
        self.Layout_IVF_2.setContentsMargins(0, 0, 0, 0)
        self.Layout_IVF_2.setObjectName("Layout_IVF_2")
        self.mark_IVF_2 = QtWidgets.QLabel(self.verticalLayoutWidget_IVF_3)
        self.mark_IVF_2.setObjectName("mark_IVF_2")
        self.Layout_IVF_2.addWidget(self.mark_IVF_2)
        self.version_IVF_2 = QtWidgets.QComboBox(self.verticalLayoutWidget_IVF_3)
        self.version_IVF_2.setObjectName("version_IVF_2")
        self.Layout_IVF_2.addWidget(self.version_IVF_2)
        self.verticalLayoutWidget_IVF_4 = QtWidgets.QWidget(self.IVF_tab)
        self.verticalLayoutWidget_IVF_4.setGeometry(QtCore.QRect(260, 140, 180, 60))
        self.verticalLayoutWidget_IVF_4.setObjectName("verticalLayoutWidget_IVF_4")
        self.Layout_IVF_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_IVF_4)
        self.Layout_IVF_3.setContentsMargins(0, 0, 0, 0)
        self.Layout_IVF_3.setObjectName("Layout_IVF_3")
        self.mark_IVF_3 = QtWidgets.QLabel(self.verticalLayoutWidget_IVF_4)
        self.mark_IVF_3.setObjectName("mark_IVF_3")
        self.Layout_IVF_3.addWidget(self.mark_IVF_3)
        self.version_IVF_3 = QtWidgets.QComboBox(self.verticalLayoutWidget_IVF_4)
        self.version_IVF_3.setObjectName("version_IVF_3")
        self.Layout_IVF_3.addWidget(self.version_IVF_3)
        self.verticalLayoutWidget_IVF_5 = QtWidgets.QWidget(self.IVF_tab)
        self.verticalLayoutWidget_IVF_5.setGeometry(QtCore.QRect(260, 200, 180, 60))
        self.verticalLayoutWidget_IVF_5.setObjectName("verticalLayoutWidget_IVF_5")
        self.Layout_IVF_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_IVF_5)
        self.Layout_IVF_4.setContentsMargins(0, 0, 0, 0)
        self.Layout_IVF_4.setObjectName("Layout_IVF_4")
        self.mark_IVF_4 = QtWidgets.QLabel(self.verticalLayoutWidget_IVF_5)
        self.mark_IVF_4.setObjectName("mark_IVF_4")
        self.Layout_IVF_4.addWidget(self.mark_IVF_4)
        self.version_IVF_4 = QtWidgets.QComboBox(self.verticalLayoutWidget_IVF_5)
        self.version_IVF_4.setObjectName("version_IVF_4")
        self.Layout_IVF_4.addWidget(self.version_IVF_4)
        self.verticalLayoutWidget_IVF_6 = QtWidgets.QWidget(self.IVF_tab)
        self.verticalLayoutWidget_IVF_6.setGeometry(QtCore.QRect(260, 260, 180, 60))
        self.verticalLayoutWidget_IVF_6.setObjectName("verticalLayoutWidget_IVF_6")
        self.Layout_IVF_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_IVF_6)
        self.Layout_IVF_5.setContentsMargins(0, 0, 0, 0)
        self.Layout_IVF_5.setObjectName("Layout_IVF_5")
        self.mark_IVF_5 = QtWidgets.QLabel(self.verticalLayoutWidget_IVF_6)
        self.mark_IVF_5.setObjectName("mark_IVF_5")
        self.Layout_IVF_5.addWidget(self.mark_IVF_5)
        self.version_IVF_5 = QtWidgets.QComboBox(self.verticalLayoutWidget_IVF_6)
        self.version_IVF_5.setObjectName("version_IVF_5")
        self.Layout_IVF_5.addWidget(self.version_IVF_5)
        self.verticalLayoutWidget_IVF_7 = QtWidgets.QWidget(self.IVF_tab)
        self.verticalLayoutWidget_IVF_7.setGeometry(QtCore.QRect(260, 320, 180, 60))
        self.verticalLayoutWidget_IVF_7.setObjectName("verticalLayoutWidget_IVF_7")
        self.Layout_IVF_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_IVF_7)
        self.Layout_IVF_6.setContentsMargins(0, 0, 0, 0)
        self.Layout_IVF_6.setObjectName("Layout_IVF_6")
        self.mark_IVF_6 = QtWidgets.QLabel(self.verticalLayoutWidget_IVF_7)
        self.mark_IVF_6.setObjectName("mark_IVF_6")
        self.Layout_IVF_6.addWidget(self.mark_IVF_6)
        self.version_IVF_6 = QtWidgets.QComboBox(self.verticalLayoutWidget_IVF_7)
        self.version_IVF_6.setObjectName("version_IVF_6")
        self.Layout_IVF_6.addWidget(self.version_IVF_6)
        self.verticalLayoutWidget_IVF_8 = QtWidgets.QWidget(self.IVF_tab)
        self.verticalLayoutWidget_IVF_8.setGeometry(QtCore.QRect(30, 380, 180, 60))
        self.verticalLayoutWidget_IVF_8.setObjectName("verticalLayoutWidget_IVF_8")
        self.Layout_IVF_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_IVF_8)
        self.Layout_IVF_7.setContentsMargins(0, 0, 0, 0)
        self.Layout_IVF_7.setObjectName("Layout_IVF_7")
        self.mark_IVF_7 = QtWidgets.QLabel(self.verticalLayoutWidget_IVF_8)
        self.mark_IVF_7.setObjectName("mark_IVF_7")
        self.Layout_IVF_7.addWidget(self.mark_IVF_7)
        self.version_IVF_7 = QtWidgets.QComboBox(self.verticalLayoutWidget_IVF_8)
        self.version_IVF_7.setObjectName("version_IVF_7")
        self.Layout_IVF_7.addWidget(self.version_IVF_7)
        self.verticalLayoutWidget_IVF_9 = QtWidgets.QWidget(self.IVF_tab)
        self.verticalLayoutWidget_IVF_9.setGeometry(QtCore.QRect(30, 20, 180, 60))
        self.verticalLayoutWidget_IVF_9.setObjectName("verticalLayoutWidget_IVF_9")
        self.Layout_IVF_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_IVF_9)
        self.Layout_IVF_8.setContentsMargins(0, 0, 0, 0)
        self.Layout_IVF_8.setObjectName("Layout_IVF_8")
        self.mark_IVF_8 = QtWidgets.QLabel(self.verticalLayoutWidget_IVF_9)
        self.mark_IVF_8.setObjectName("mark_IVF_8")
        self.Layout_IVF_8.addWidget(self.mark_IVF_8)
        self.version_IVF_8 = QtWidgets.QComboBox(self.verticalLayoutWidget_IVF_9)
        self.version_IVF_8.setObjectName("version_IVF_8")
        self.Layout_IVF_8.addWidget(self.version_IVF_8)
        self.verticalLayoutWidget_IVF_10 = QtWidgets.QWidget(self.IVF_tab)
        self.verticalLayoutWidget_IVF_10.setGeometry(QtCore.QRect(30, 80, 180, 60))
        self.verticalLayoutWidget_IVF_10.setObjectName("verticalLayoutWidget_IVF_10")
        self.Layout_IVF_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_IVF_10)
        self.Layout_IVF_9.setContentsMargins(0, 0, 0, 0)
        self.Layout_IVF_9.setObjectName("Layout_IVF_9")
        self.mark_IVF_9 = QtWidgets.QLabel(self.verticalLayoutWidget_IVF_10)
        self.mark_IVF_9.setObjectName("mark_IVF_9")
        self.Layout_IVF_9.addWidget(self.mark_IVF_9)
        self.version_IVF_9 = QtWidgets.QComboBox(self.verticalLayoutWidget_IVF_10)
        self.version_IVF_9.setObjectName("version_IVF_9")
        self.Layout_IVF_9.addWidget(self.version_IVF_9)
        self.verticalLayoutWidget_IVF_11 = QtWidgets.QWidget(self.IVF_tab)
        self.verticalLayoutWidget_IVF_11.setGeometry(QtCore.QRect(30, 140, 180, 60))
        self.verticalLayoutWidget_IVF_11.setObjectName("verticalLayoutWidget_IVF_11")
        self.Layout_IVF_10 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_IVF_11)
        self.Layout_IVF_10.setContentsMargins(0, 0, 0, 0)
        self.Layout_IVF_10.setObjectName("Layout_IVF_10")
        self.mark_IVF_10 = QtWidgets.QLabel(self.verticalLayoutWidget_IVF_11)
        self.mark_IVF_10.setObjectName("mark_IVF_10")
        self.Layout_IVF_10.addWidget(self.mark_IVF_10)
        self.version_IVF_10 = QtWidgets.QComboBox(self.verticalLayoutWidget_IVF_11)
        self.version_IVF_10.setObjectName("version_IVF_10")
        self.Layout_IVF_10.addWidget(self.version_IVF_10)
        self.verticalLayoutWidget_IVF_12 = QtWidgets.QWidget(self.IVF_tab)
        self.verticalLayoutWidget_IVF_12.setGeometry(QtCore.QRect(30, 200, 180, 60))
        self.verticalLayoutWidget_IVF_12.setObjectName("verticalLayoutWidget_IVF_12")
        self.Layout_IVF_11 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_IVF_12)
        self.Layout_IVF_11.setContentsMargins(0, 0, 0, 0)
        self.Layout_IVF_11.setObjectName("Layout_IVF_11")
        self.mark_IVF_11 = QtWidgets.QLabel(self.verticalLayoutWidget_IVF_12)
        self.mark_IVF_11.setObjectName("mark_IVF_11")
        self.Layout_IVF_11.addWidget(self.mark_IVF_11)
        self.version_IVF_11 = QtWidgets.QComboBox(self.verticalLayoutWidget_IVF_12)
        self.version_IVF_11.setObjectName("version_IVF_11")
        self.Layout_IVF_11.addWidget(self.version_IVF_11)
        self.verticalLayoutWidget_IVF_13 = QtWidgets.QWidget(self.IVF_tab)
        self.verticalLayoutWidget_IVF_13.setGeometry(QtCore.QRect(30, 260, 180, 60))
        self.verticalLayoutWidget_IVF_13.setObjectName("verticalLayoutWidget_IVF_13")
        self.Layout_IVF_12 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_IVF_13)
        self.Layout_IVF_12.setContentsMargins(0, 0, 0, 0)
        self.Layout_IVF_12.setObjectName("Layout_IVF_12")
        self.mark_IVF_12 = QtWidgets.QLabel(self.verticalLayoutWidget_IVF_13)
        self.mark_IVF_12.setObjectName("mark_IVF_12")
        self.Layout_IVF_12.addWidget(self.mark_IVF_12)
        self.version_IVF_12 = QtWidgets.QComboBox(self.verticalLayoutWidget_IVF_13)
        self.version_IVF_12.setObjectName("version_IVF_12")
        self.Layout_IVF_12.addWidget(self.version_IVF_12)
        self.verticalLayoutWidget_IVF_14 = QtWidgets.QWidget(self.IVF_tab)
        self.verticalLayoutWidget_IVF_14.setGeometry(QtCore.QRect(30, 320, 180, 60))
        self.verticalLayoutWidget_IVF_14.setObjectName("verticalLayoutWidget_IVF_14")
        self.Layout_IVF_13 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_IVF_14)
        self.Layout_IVF_13.setContentsMargins(0, 0, 0, 0)
        self.Layout_IVF_13.setObjectName("Layout_IVF_13")
        self.mark_IVF_13 = QtWidgets.QLabel(self.verticalLayoutWidget_IVF_14)
        self.mark_IVF_13.setObjectName("mark_IVF_13")
        self.Layout_IVF_13.addWidget(self.mark_IVF_13)
        self.version_IVF_13 = QtWidgets.QComboBox(self.verticalLayoutWidget_IVF_14)
        self.version_IVF_13.setObjectName("version_IVF_13")
        self.Layout_IVF_13.addWidget(self.version_IVF_13)

        # 下拉框内容更改时
        self.version_IVF_1.activated.connect(lambda: self.choose_item(self.version_IVF_1.currentText(), 1, 4))
        self.version_IVF_2.activated.connect(lambda: self.choose_item(self.version_IVF_2.currentText(), 2, 4))
        self.version_IVF_3.activated.connect(lambda: self.choose_item(self.version_IVF_3.currentText(), 3, 4))
        self.version_IVF_4.activated.connect(lambda: self.choose_item(self.version_IVF_4.currentText(), 4, 4))
        self.version_IVF_5.activated.connect(lambda: self.choose_item(self.version_IVF_5.currentText(), 5, 4))
        self.version_IVF_6.activated.connect(lambda: self.choose_item(self.version_IVF_6.currentText(), 6, 4))
        self.version_IVF_7.activated.connect(lambda: self.choose_item(self.version_IVF_7.currentText(), 7, 4))
        self.version_IVF_8.activated.connect(lambda: self.choose_item(self.version_IVF_8.currentText(), 8, 4))
        self.version_IVF_9.activated.connect(lambda: self.choose_item(self.version_IVF_9.currentText(), 9, 4))
        self.version_IVF_10.activated.connect(lambda: self.choose_item(self.version_IVF_10.currentText(), 10, 4))
        self.version_IVF_11.activated.connect(lambda: self.choose_item(self.version_IVF_11.currentText(), 11, 4))
        self.version_IVF_12.activated.connect(lambda: self.choose_item(self.version_IVF_12.currentText(), 12, 4))
        self.version_IVF_13.activated.connect(lambda: self.choose_item(self.version_IVF_13.currentText(), 13, 4))

    # BC孕周类型的标记物大小位置设置
    def test_item_BC_setting(self):
        self.verticalLayoutWidget_BC_2 = QtWidgets.QWidget(self.BC_tab)
        self.verticalLayoutWidget_BC_2.setGeometry(QtCore.QRect(260, 20, 180, 60))
        self.verticalLayoutWidget_BC_2.setObjectName("verticalLayoutWidget_BC_2")
        self.Layout_BC_1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_BC_2)
        self.Layout_BC_1.setContentsMargins(0, 0, 0, 0)
        self.Layout_BC_1.setObjectName("Layout_BC_1")
        self.mark_BC_1 = QtWidgets.QLabel(self.verticalLayoutWidget_BC_2)
        self.mark_BC_1.setObjectName("mark_BC_1")
        self.Layout_BC_1.addWidget(self.mark_BC_1)
        self.version_BC_1 = QtWidgets.QComboBox(self.verticalLayoutWidget_BC_2)
        self.version_BC_1.setObjectName("version_BC_1")
        self.Layout_BC_1.addWidget(self.version_BC_1)
        self.verticalLayoutWidget_BC_3 = QtWidgets.QWidget(self.BC_tab)
        self.verticalLayoutWidget_BC_3.setGeometry(QtCore.QRect(260, 80, 180, 60))
        self.verticalLayoutWidget_BC_3.setObjectName("verticalLayoutWidget_BC_3")
        self.Layout_BC_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_BC_3)
        self.Layout_BC_2.setContentsMargins(0, 0, 0, 0)
        self.Layout_BC_2.setObjectName("Layout_BC_2")
        self.mark_BC_2 = QtWidgets.QLabel(self.verticalLayoutWidget_BC_3)
        self.mark_BC_2.setObjectName("mark_BC_2")
        self.Layout_BC_2.addWidget(self.mark_BC_2)
        self.version_BC_2 = QtWidgets.QComboBox(self.verticalLayoutWidget_BC_3)
        self.version_BC_2.setObjectName("version_BC_2")
        self.Layout_BC_2.addWidget(self.version_BC_2)
        self.verticalLayoutWidget_BC_4 = QtWidgets.QWidget(self.BC_tab)
        self.verticalLayoutWidget_BC_4.setGeometry(QtCore.QRect(260, 140, 180, 60))
        self.verticalLayoutWidget_BC_4.setObjectName("verticalLayoutWidget_BC_4")
        self.Layout_BC_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_BC_4)
        self.Layout_BC_3.setContentsMargins(0, 0, 0, 0)
        self.Layout_BC_3.setObjectName("Layout_BC_3")
        self.mark_BC_3 = QtWidgets.QLabel(self.verticalLayoutWidget_BC_4)
        self.mark_BC_3.setObjectName("mark_BC_3")
        self.Layout_BC_3.addWidget(self.mark_BC_3)
        self.version_BC_3 = QtWidgets.QComboBox(self.verticalLayoutWidget_BC_4)
        self.version_BC_3.setObjectName("version_BC_3")
        self.Layout_BC_3.addWidget(self.version_BC_3)
        self.verticalLayoutWidget_BC_5 = QtWidgets.QWidget(self.BC_tab)
        self.verticalLayoutWidget_BC_5.setGeometry(QtCore.QRect(260, 200, 180, 60))
        self.verticalLayoutWidget_BC_5.setObjectName("verticalLayoutWidget_BC_5")
        self.Layout_BC_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_BC_5)
        self.Layout_BC_4.setContentsMargins(0, 0, 0, 0)
        self.Layout_BC_4.setObjectName("Layout_BC_4")
        self.mark_BC_4 = QtWidgets.QLabel(self.verticalLayoutWidget_BC_5)
        self.mark_BC_4.setObjectName("mark_BC_4")
        self.Layout_BC_4.addWidget(self.mark_BC_4)
        self.version_BC_4 = QtWidgets.QComboBox(self.verticalLayoutWidget_BC_5)
        self.version_BC_4.setObjectName("version_BC_4")
        self.Layout_BC_4.addWidget(self.version_BC_4)
        self.verticalLayoutWidget_BC_6 = QtWidgets.QWidget(self.BC_tab)
        self.verticalLayoutWidget_BC_6.setGeometry(QtCore.QRect(260, 260, 180, 60))
        self.verticalLayoutWidget_BC_6.setObjectName("verticalLayoutWidget_BC_6")
        self.Layout_BC_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_BC_6)
        self.Layout_BC_5.setContentsMargins(0, 0, 0, 0)
        self.Layout_BC_5.setObjectName("Layout_BC_5")
        self.mark_BC_5 = QtWidgets.QLabel(self.verticalLayoutWidget_BC_6)
        self.mark_BC_5.setObjectName("mark_BC_5")
        self.Layout_BC_5.addWidget(self.mark_BC_5)
        self.version_BC_5 = QtWidgets.QComboBox(self.verticalLayoutWidget_BC_6)
        self.version_BC_5.setObjectName("version_BC_5")
        self.Layout_BC_5.addWidget(self.version_BC_5)
        self.verticalLayoutWidget_BC_7 = QtWidgets.QWidget(self.BC_tab)
        self.verticalLayoutWidget_BC_7.setGeometry(QtCore.QRect(260, 320, 180, 60))
        self.verticalLayoutWidget_BC_7.setObjectName("verticalLayoutWidget_BC_7")
        self.Layout_BC_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_BC_7)
        self.Layout_BC_6.setContentsMargins(0, 0, 0, 0)
        self.Layout_BC_6.setObjectName("Layout_BC_6")
        self.mark_BC_6 = QtWidgets.QLabel(self.verticalLayoutWidget_BC_7)
        self.mark_BC_6.setObjectName("mark_BC_6")
        self.Layout_BC_6.addWidget(self.mark_BC_6)
        self.version_BC_6 = QtWidgets.QComboBox(self.verticalLayoutWidget_BC_7)
        self.version_BC_6.setObjectName("version_BC_6")
        self.Layout_BC_6.addWidget(self.version_BC_6)
        self.verticalLayoutWidget_BC_8 = QtWidgets.QWidget(self.BC_tab)
        self.verticalLayoutWidget_BC_8.setGeometry(QtCore.QRect(30, 380, 180, 60))
        self.verticalLayoutWidget_BC_8.setObjectName("verticalLayoutWidget_BC_8")
        self.Layout_BC_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_BC_8)
        self.Layout_BC_7.setContentsMargins(0, 0, 0, 0)
        self.Layout_BC_7.setObjectName("Layout_BC_7")
        self.mark_BC_7 = QtWidgets.QLabel(self.verticalLayoutWidget_BC_8)
        self.mark_BC_7.setObjectName("mark_BC_7")
        self.Layout_BC_7.addWidget(self.mark_BC_7)
        self.version_BC_7 = QtWidgets.QComboBox(self.verticalLayoutWidget_BC_8)
        self.version_BC_7.setObjectName("version_BC_7")
        self.Layout_BC_7.addWidget(self.version_BC_7)
        self.verticalLayoutWidget_BC_9 = QtWidgets.QWidget(self.BC_tab)
        self.verticalLayoutWidget_BC_9.setGeometry(QtCore.QRect(30, 20, 180, 60))
        self.verticalLayoutWidget_BC_9.setObjectName("verticalLayoutWidget_BC_9")
        self.Layout_BC_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_BC_9)
        self.Layout_BC_8.setContentsMargins(0, 0, 0, 0)
        self.Layout_BC_8.setObjectName("Layout_BC_8")
        self.mark_BC_8 = QtWidgets.QLabel(self.verticalLayoutWidget_BC_9)
        self.mark_BC_8.setObjectName("mark_BC_8")
        self.Layout_BC_8.addWidget(self.mark_BC_8)
        self.version_BC_8 = QtWidgets.QComboBox(self.verticalLayoutWidget_BC_9)
        self.version_BC_8.setObjectName("version_BC_8")
        self.Layout_BC_8.addWidget(self.version_BC_8)
        self.verticalLayoutWidget_BC_10 = QtWidgets.QWidget(self.BC_tab)
        self.verticalLayoutWidget_BC_10.setGeometry(QtCore.QRect(30, 80, 180, 60))
        self.verticalLayoutWidget_BC_10.setObjectName("verticalLayoutWidget_BC_10")
        self.Layout_BC_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_BC_10)
        self.Layout_BC_9.setContentsMargins(0, 0, 0, 0)
        self.Layout_BC_9.setObjectName("Layout_BC_9")
        self.mark_BC_9 = QtWidgets.QLabel(self.verticalLayoutWidget_BC_10)
        self.mark_BC_9.setObjectName("mark_BC_9")
        self.Layout_BC_9.addWidget(self.mark_BC_9)
        self.version_BC_9 = QtWidgets.QComboBox(self.verticalLayoutWidget_BC_10)
        self.version_BC_9.setObjectName("version_BC_9")
        self.Layout_BC_9.addWidget(self.version_BC_9)
        self.verticalLayoutWidget_BC_11 = QtWidgets.QWidget(self.BC_tab)
        self.verticalLayoutWidget_BC_11.setGeometry(QtCore.QRect(30, 140, 180, 60))
        self.verticalLayoutWidget_BC_11.setObjectName("verticalLayoutWidget_BC_11")
        self.Layout_BC_10 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_BC_11)
        self.Layout_BC_10.setContentsMargins(0, 0, 0, 0)
        self.Layout_BC_10.setObjectName("Layout_BC_10")
        self.mark_BC_10 = QtWidgets.QLabel(self.verticalLayoutWidget_BC_11)
        self.mark_BC_10.setObjectName("mark_BC_10")
        self.Layout_BC_10.addWidget(self.mark_BC_10)
        self.version_BC_10 = QtWidgets.QComboBox(self.verticalLayoutWidget_BC_11)
        self.version_BC_10.setObjectName("version_BC_10")
        self.Layout_BC_10.addWidget(self.version_BC_10)
        self.verticalLayoutWidget_BC_12 = QtWidgets.QWidget(self.BC_tab)
        self.verticalLayoutWidget_BC_12.setGeometry(QtCore.QRect(30, 200, 180, 60))
        self.verticalLayoutWidget_BC_12.setObjectName("verticalLayoutWidget_BC_12")
        self.Layout_BC_11 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_BC_12)
        self.Layout_BC_11.setContentsMargins(0, 0, 0, 0)
        self.Layout_BC_11.setObjectName("Layout_BC_11")
        self.mark_BC_11 = QtWidgets.QLabel(self.verticalLayoutWidget_BC_12)
        self.mark_BC_11.setObjectName("mark_BC_11")
        self.Layout_BC_11.addWidget(self.mark_BC_11)
        self.version_BC_11 = QtWidgets.QComboBox(self.verticalLayoutWidget_BC_12)
        self.version_BC_11.setObjectName("version_BC_11")
        self.Layout_BC_11.addWidget(self.version_BC_11)
        self.verticalLayoutWidget_BC_13 = QtWidgets.QWidget(self.BC_tab)
        self.verticalLayoutWidget_BC_13.setGeometry(QtCore.QRect(30, 260, 180, 60))
        self.verticalLayoutWidget_BC_13.setObjectName("verticalLayoutWidget_BC_13")
        self.Layout_BC_12 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_BC_13)
        self.Layout_BC_12.setContentsMargins(0, 0, 0, 0)
        self.Layout_BC_12.setObjectName("Layout_BC_12")
        self.mark_BC_12 = QtWidgets.QLabel(self.verticalLayoutWidget_BC_13)
        self.mark_BC_12.setObjectName("mark_BC_12")
        self.Layout_BC_12.addWidget(self.mark_BC_12)
        self.version_BC_12 = QtWidgets.QComboBox(self.verticalLayoutWidget_BC_13)
        self.version_BC_12.setObjectName("version_BC_12")
        self.Layout_BC_12.addWidget(self.version_BC_12)
        self.verticalLayoutWidget_BC_14 = QtWidgets.QWidget(self.BC_tab)
        self.verticalLayoutWidget_BC_14.setGeometry(QtCore.QRect(30, 320, 180, 60))
        self.verticalLayoutWidget_BC_14.setObjectName("verticalLayoutWidget_BC_14")
        self.Layout_BC_13 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_BC_14)
        self.Layout_BC_13.setContentsMargins(0, 0, 0, 0)
        self.Layout_BC_13.setObjectName("Layout_BC_13")
        self.mark_BC_13 = QtWidgets.QLabel(self.verticalLayoutWidget_BC_14)
        self.mark_BC_13.setObjectName("mark_BC_13")
        self.Layout_BC_13.addWidget(self.mark_BC_13)
        self.version_BC_13 = QtWidgets.QComboBox(self.verticalLayoutWidget_BC_14)
        self.version_BC_13.setObjectName("version_BC_13")
        self.Layout_BC_13.addWidget(self.version_BC_13)

        # 下拉框内容更改时
        self.version_BC_1.activated.connect(lambda: self.choose_item(self.version_BC_1.currentText(), 1, 5))
        self.version_BC_2.activated.connect(lambda: self.choose_item(self.version_BC_2.currentText(), 2, 5))
        self.version_BC_3.activated.connect(lambda: self.choose_item(self.version_BC_3.currentText(), 3, 5))
        self.version_BC_4.activated.connect(lambda: self.choose_item(self.version_BC_4.currentText(), 4, 5))
        self.version_BC_5.activated.connect(lambda: self.choose_item(self.version_BC_5.currentText(), 5, 5))
        self.version_BC_6.activated.connect(lambda: self.choose_item(self.version_BC_6.currentText(), 6, 5))
        self.version_BC_7.activated.connect(lambda: self.choose_item(self.version_BC_7.currentText(), 7, 5))
        self.version_BC_8.activated.connect(lambda: self.choose_item(self.version_BC_8.currentText(), 8, 5))
        self.version_BC_9.activated.connect(lambda: self.choose_item(self.version_BC_9.currentText(), 9, 5))
        self.version_BC_10.activated.connect(lambda: self.choose_item(self.version_BC_10.currentText(), 10, 5))
        self.version_BC_11.activated.connect(lambda: self.choose_item(self.version_BC_11.currentText(), 11, 5))
        self.version_BC_12.activated.connect(lambda: self.choose_item(self.version_BC_12.currentText(), 12, 5))
        self.version_BC_13.activated.connect(lambda: self.choose_item(self.version_BC_13.currentText(), 13, 5))

    #LMP_标记物版本设置
    def LMP_content_filling(self):
        version = self.connect.version_testItem_gestation(1)
        for row in version:
            if row.TestItemID == 1:
                self.version_LMP_1.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 2:
                self.version_LMP_2.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 3:
                self.version_LMP_3.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 4:
                self.version_LMP_4.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 5:
                self.version_LMP_5.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 6:
                self.version_LMP_6.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 7:
                self.version_LMP_7.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 8:
                self.version_LMP_8.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 9:
                self.version_LMP_9.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 10:
                self.version_LMP_10.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 11:
                self.version_LMP_11.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 12:
                self.version_LMP_12.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 13:
                self.version_LMP_13.addItem((str)(row.MedianVerNo) + "  " + row.date)

    # BPD_标记物版本设置
    def BPD_content_filling(self):
        version = self.connect.version_testItem_gestation(2)
        for row in version:
            if row.TestItemID == 1:
                self.version_BPD_1.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 2:
                self.version_BPD_2.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 3:
                self.version_BPD_3.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 4:
                self.version_BPD_4.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 5:
                self.version_BPD_5.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 6:
                self.version_BPD_6.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 7:
                self.version_BPD_7.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 8:
                self.version_BPD_8.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 9:
                self.version_BPD_9.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 10:
                self.version_BPD_10.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 11:
                self.version_BPD_11.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 12:
                self.version_BPD_12.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 13:
                self.version_BPD_13.addItem((str)(row.MedianVerNo) + "  " + row.date)

    # CRL_标记物版本设置
    def CRL_content_filling(self):
        version = self.connect.version_testItem_gestation(3)
        for row in version:
            if row.TestItemID == 1:
                self.version_CRL_1.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 2:
                self.version_CRL_2.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 3:
                self.version_CRL_3.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 4:
                self.version_CRL_4.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 5:
                self.version_CRL_5.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 6:
                self.version_CRL_6.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 7:
                self.version_CRL_7.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 8:
                self.version_CRL_8.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 9:
                self.version_CRL_9.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 10:
                self.version_CRL_10.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 11:
                self.version_CRL_11.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 12:
                self.version_CRL_12.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 13:
                self.version_CRL_13.addItem((str)(row.MedianVerNo) + "  " + row.date)

    # IVF_标记物版本设置
    def IVF_content_filling(self):
        version = self.connect.version_testItem_gestation(4)
        for row in version:
            if row.TestItemID == 1:
                self.version_IVF_1.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 2:
                self.version_IVF_2.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 3:
                self.version_IVF_3.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 4:
                self.version_IVF_4.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 5:
                self.version_IVF_5.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 6:
                self.version_IVF_6.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 7:
                self.version_IVF_7.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 8:
                self.version_IVF_8.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 9:
                self.version_IVF_9.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 10:
                self.version_IVF_10.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 11:
                self.version_IVF_11.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 12:
                self.version_IVF_12.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 13:
                self.version_IVF_13.addItem((str)(row.MedianVerNo) + "  " + row.date)

    # BC_标记物版本设置
    def BC_content_filling(self):
        version = self.connect.version_testItem_gestation(5)
        for row in version:
            if row.TestItemID == 1:
                self.version_BC_1.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 2:
                self.version_BC_2.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 3:
                self.version_BC_3.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 4:
                self.version_BC_4.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 5:
                self.version_BC_5.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 6:
                self.version_BC_6.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 7:
                self.version_BC_7.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 8:
                self.version_BC_8.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 9:
                self.version_BC_9.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 10:
                self.version_BC_10.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 11:
                self.version_BC_11.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 12:
                self.version_BC_12.addItem((str)(row.MedianVerNo) + "  " + row.date)
            elif row.TestItemID == 13:
                self.version_BC_13.addItem((str)(row.MedianVerNo) + "  " + row.date)

    # 右侧标记物某个版本某个孕周的具体内容
    def table_view_setting(self):
        self.tableWidget = QtWidgets.QTableWidget(self)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setGeometry(QtCore.QRect(600, 130, 480, 510))
        self.tableWidget.setAutoScroll(False)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)

    # 标记物序号名称转换
    def convert_item(self, num):
        if num == 1:
            return "AFP_M"
        if num == 2:
            return "tbhCG_M"
        if num == 3:
            return "uE3_M"
        if num == 4:
            return "InhA_M"
        if num == 5:
            return "fbhCG_M"
        if num == 6:
            return "PAPPA_M"
        if num == 7:
            return "NT_E"
        if num == 8:
            return "AFP_E"
        if num == 9:
            return "tbhCG_E"
        if num == 10:
            return "uE3_E"
        if num == 11:
            return "InhA_E"
        if num == 12:
            return "fbhCG_E"
        if num == 13:
            return "PAPPA_E"

    # 当选中某一个标记物时, 将这个版本的标记物的所有值显示在右边表格中
    def choose_item(self, median_no, item_id, gestation_type):
        yunzhou = self.tabWidget.currentWidget().objectName().split("_tab")[0]
        self.table_title.setText("当前列表：%s, %s 版本号:%s" % (yunzhou, self.convert_item(item_id), median_no))
        median_no = int(median_no.split("  ")[0])
        if median_no == 1:
            gestation_type = 0
        data = self.connect.median_version_query(median_no, item_id, gestation_type)
        self.tableWidget.setRowCount(len(data))
        for i in range(0, len(data)):
            self.tableWidget.setItem(i, 0, QTableWidgetItem(str(format(data[i][0], '.1f'))))
            self.tableWidget.setItem(i, 1, QTableWidgetItem(str(format(data[i][1], '.2f'))))
            self.tableWidget.setItem(i, 2, QTableWidgetItem(data[i][2]))


if __name__ == '__main__':

    app = QApplication(sys.argv)
    main_win = UiMedian()

    main_win.show()
    sys.exit(app.exec_())